"use client";
import { cn } from "@/lib/utils";
const sM:Record<string,{b:string;t:string;d:string}>={executed:{b:"bg-mint/10",t:"text-mint",d:"bg-mint shadow-[0_0_6px_#00d4aa]"},pending:{b:"bg-amber/10",t:"text-amber",d:"bg-amber shadow-[0_0_6px_#ffc107]"},pending_approval:{b:"bg-amber/10",t:"text-amber",d:"bg-amber shadow-[0_0_6px_#ffc107] animate-pulse"},approved:{b:"bg-mint/10",t:"text-mint",d:"bg-mint"},rejected:{b:"bg-zinc-500/10",t:"text-zinc-400",d:"bg-zinc-400"},dry_run:{b:"bg-iris/10",t:"text-iris",d:"bg-iris"},filtered:{b:"bg-zinc-700/10",t:"text-zinc-500",d:"bg-zinc-600"},failed:{b:"bg-coral/10",t:"text-coral",d:"bg-coral shadow-[0_0_6px_#ff4757]"},skipped:{b:"bg-zinc-500/10",t:"text-zinc-400",d:"bg-zinc-400"},active:{b:"bg-mint/10",t:"text-mint",d:"bg-mint shadow-[0_0_6px_#00d4aa]"},paused:{b:"bg-amber/10",t:"text-amber",d:"bg-amber shadow-[0_0_6px_#ffc107]"},running:{b:"bg-mint/10",t:"text-mint",d:"bg-mint shadow-[0_0_6px_#00d4aa]"},stopped:{b:"bg-coral/10",t:"text-coral",d:"bg-coral"},live:{b:"bg-mint/10",t:"text-mint",d:"bg-mint shadow-[0_0_6px_#00d4aa]"}};

export function Badge({s}:{s:string}){const st=sM[s]||sM.pending;const label:Record<string,string>={pending_approval:"pending",dry_run:"dry run"};return<span className={cn("inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[11px] font-semibold uppercase tracking-wider",st.b,st.t)}><span className={cn("w-1.5 h-1.5 rounded-full",st.d)}/>{label[s]||s}</span>;}

export function Pnl({v,sz="md"}:{v:number;sz?:"sm"|"md"|"lg"}){const p=v>=0;return<span className={cn("font-mono font-bold inline-flex items-center gap-0.5",p?"text-mint":"text-coral",{sm:"text-xs",md:"text-sm",lg:"text-xl"}[sz])}>{p?"▲":"▼"}{p?"+":""}{Math.abs(v).toLocaleString("en-US",{style:"currency",currency:"USD"})}</span>;}

export function Spark({data,color="#00d4aa",w=120,h=32}:{data:number[];color?:string;w?:number;h?:number}){if(!data||data.length<2)return null;const mn=Math.min(...data),mx=Math.max(...data),r=mx-mn||1;const pts=data.map((v,i)=>`${(i/(data.length-1))*w},${h-((v-mn)/r)*h}`).join(" ");const g=`g${w}${h}`;return<svg width={w} height={h} className="block"><defs><linearGradient id={g} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={color} stopOpacity=".3"/><stop offset="100%" stopColor={color} stopOpacity="0"/></linearGradient></defs><polygon points={`0,${h} ${pts} ${w},${h}`} fill={`url(#${g})`}/><polyline points={pts} fill="none" stroke={color} strokeWidth="1.5" strokeLinecap="round"/></svg>;}

export function Toggle({v,onChange}:{v:boolean;onChange:(v:boolean)=>void}){return<button onClick={()=>onChange(!v)} className={cn("relative w-11 h-6 rounded-full transition-colors",v?"bg-mint":"bg-edge-1")}><div className={cn("absolute top-[3px] w-[18px] h-[18px] rounded-full bg-white transition-[left]",v?"left-[23px]":"left-[3px]")}/></button>;}

export function Pill({children,color="#818cf8"}:{children:React.ReactNode;color?:string}){return<span className="inline-flex px-2 py-0.5 rounded-xl text-[11px] font-semibold" style={{backgroundColor:`${color}18`,color}}>{children}</span>;}
export function Tag({children}:{children:React.ReactNode}){return<span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-md bg-iris/10 text-iris text-[11px] font-medium">{children}</span>;}
export function Card({children,className}:{children:React.ReactNode;className?:string}){return<div className={cn("bg-bg-3 border border-edge-1 rounded-xl p-5",className)}>{children}</div>;}
export function Stat({label,children,sub}:{label:string;children:React.ReactNode;sub?:React.ReactNode}){return<Card><div className="text-[11px] text-zinc-500 uppercase tracking-wider mb-1.5">{label}</div><div className="text-[22px] font-bold font-mono tracking-tight">{children}</div>{sub&&<div className="text-[11px] text-zinc-500 mt-1">{sub}</div>}</Card>;}
export const TH=({children}:{children:React.ReactNode})=><th className="px-3 py-2 text-left text-[11px] text-zinc-500 uppercase tracking-wider font-medium">{children}</th>;
export const TD=({children,className}:{children:React.ReactNode;className?:string})=><td className={cn("px-3 py-2.5 text-xs",className)}>{children}</td>;
export function LoadingDots(){return<div className="flex gap-1 items-center justify-center py-8"><div className="w-2 h-2 rounded-full bg-mint animate-pulse"/><div className="w-2 h-2 rounded-full bg-mint animate-pulse"/><div className="w-2 h-2 rounded-full bg-mint animate-pulse"/></div>;}
export function EmptyState({msg}:{msg:string}){return<div className="text-center py-12 text-zinc-500">{msg}</div>;}
